dylanaraps/pywal

- setup.py
> General: fix console_script entry_point. Closes #9

- pywal/__main__.py
Very rudimentarily solves #13 I guess...
> Add -f flag to read colorscheme from file

- pywal/reload.py
Not sure if this is the "right" way, but polybar doesn't seem to reload unless its configuration is touched, so could we try this?
> reload: Try to reload polybar

- pywal/colors.py
- pywal/util.py
- tests/test_util.py
This PR darkens the generated background color based on it's brightness. This fixes issues with the background color blending in with the wallpaper and makes things look a lot nicer imo.
Here's some screenies:
Before:
After:
> colors: Darken bg if contrast is too low.

- pywal/wallpaper.py
This PR aims to add wallpaper setting support to macOS.
@aeikenberry can you test this and let me know if the wallpaper is set correctly?
> wallpaper: Add support for macOS

- pywal/sequences.py
https://iterm2.com/documentation-escape-codes.html
> Adds support for changing tab bar color in iTerm

- pywal/colors.py
- pywal/util.py
- tests/test_util.py
This PR makes the comment color a lightened version of the background color instead of a hardcoded grey color.
> colors: un-hardcode comment color.

- tests/test_main.py
You're too fast! Meant to include a test for -e
> Adds test for -e

- pywal/reload.py
I thought maybe that specific theme could be optional for running the reload script.
> Theme is optional for GTK refresh

- .travis.yml
- pywal/__main__.py
- pywal/colors.py
- pywal/export.py
- pywal/image.py
- pywal/reload.py
- pywal/sequences.py
- pywal/settings.py
- pywal/util.py
- pywal/wallpaper.py
- setup.py
- tests/test_export.py
- tests/test_main.py
- tests/test_sequences.py
- tests/test_util.py
> general: Add support for Python 3.5

- pywal/util.py
Fixes the file not found error on Windows.
> windows: Fix file not found error.

- .travis.yml
- tests/test_sequences.py
I added some OS detection to the unittests so that they will compare the right escape sequences.  If someone could verify that the sequences I'm checking against are correct that would be awesome.  This should be able to close #103
> Fixed Unittests on MacOS

- .travis.yml
- tests/test_sequences.py
> travis: Add macOS testing

- pywal/sequences.py
- tests/test_sequences.py
Pywal was using sequences that iterm2 recommends against.  See https://iterm2.com/documentation-escape-codes.html
> Fixed Issue #100

- .pylintrc
- pywal/__main__.py
- pywal/colors.py
- pywal/util.py
> colors: Add light theme support.

- pywal/colors.py
- pywal/util.py
Addresses https://github.com/dylanaraps/pywal/issues/307. As mentioned there, there are two open questions here:
1. Whether `md5` is appropriate for this application (over, say, `sha256`).
2. Whether this should be an optional feature or the default.
> Hash file for cache filename

- pywal/colors.py
- pywal/util.py
> Revert "Hash file for cache filename"

- pywal/templates/colors-rofi-dark.rasi
- pywal/templates/colors-rofi-light.rasi
Fix missing hashes in rofi templates that may break some i3 configs
> Fix rofi templates

- pywal/reload.py
Automatically reload bspwm when wal is invoked.
> reload: support for bspwm

- pywal/sequences.py
- pywal/wallpaper.py
Fix for Issue #330: MacOS Mojave Dock crash
> Issues #330 & #382: MacOS bug fixes

- pywal/wallpaper.py
Using some regex I was able to allow pywal to set the wallpaper on all monitors in xfce versions > 4.12. Should still work in older versions as the xfconf paths for xfce < 4.12 are also matched by the regex.
> Add support for setting wallpaper in xfce > 4.12

- pywal/util.py
These give access to separate RGB values in the range from 0 to 1, e.g. needed by compton/picom shadows.
In `compton.conf`:
`shadow-red = {color0.red};`
`shadow-green = {color0.green};`
`shadow-blue = {color0.blue};`
> Added red, green and blue properties to Color class. 

- pywal/util.py
I needed this for configuring the colors of the mgba emulator.
> Add decimal output support

- pywal/export.py
- pywal/templates/colors-nqq.css
- pywal/wallpaper.py
> Plasma support 0.2

- pywal/wallpaper.py
With this change, pywal can now identify the KDE Plasma desktop environment correctly and update the wallpaper.  Tested on Plasma 5.19.4
> Added support for changing wallpaper on KDE Plasma.

- pywal/export.py
- pywal/templates/colors-nqq.css
- pywal/wallpaper.py
Added a built-in .css theme template for Notepadqq along
> Notepadqq theme

- pywal/wallpaper.py
Fixes #515 
- Append to the data table, rewrite the preferences table.
> #515 MacOS - Dock crash fix v2

- pywal/export.py
It used to cause error every tests.
> [Test] Fix longline for flake8

- pywal/templates/colors-themer.js
Themer is a great OSS which generates various editor themes, terminal themes, and themes for other apps.
https://github.com/mjswensen/themer
Themer can run with user color-set. 
I'd like to make color-set with pywal.
So I created PR.
> [Feature] Add themer template
