dylanaraps/pywal

.travis.yml
pywal/__init__.py
setup.py

- Switch to distributing pywal as a module and having setuptools register
the script as an console_script entry point.
- Added python_requires field to setuptools.setup.
- Use the module version as the package version.

Use setuptools.setup console_scripts entry point.

---

pywal/colors.py
pywal/sequences.py
pywal/settings.py

This PR adds support for macOS (iTerm2 only).
Can those with access to a macOS machine with iTerm2 test this PR for me? 
TODO:
**Those of you using macOS and would like to help test:**
Do any of these commands change iTerm2's background color to `#FFFFFF`?
```sh
printf "%b\n" "\033]\a1337;SetColors=bg=FFFFFF"
printf "%b\n" "\033]PhFFFFFF\033\\"
```
Sources: 
- https://www.iterm2.com/documentation-escape-codes.html
- https://github.com/gnachman/iTerm2/blob/master/tests/setpal
- https://gitlab.com/gnachman/iterm2/issues/454
- https://github.com/gnachman/iTerm2/blob/master/tests/set_colors.applescript
- https://github.com/gnachman/iTerm2/blob/master/tests/it2setcolor

os: Add support for macOS (Take 2)

---

pywal/__main__.py
pywal/wallpaper.py
tests/test_sequences.py

On mac, the reload env function is opening up the x11 app for me, and if it's not already open, makes wal super slow. This adds an option to bypass this.

Fixes reload wallpaper weirdness and adds -e option

---

pywal/templates/colors.Xresources

This PR uses `{background.alpha}` for `URxvt*borderColor` in the Xresources template so that `urxvt` terminal borders share the same transparency as the terminal background.
For example, this is `xrdb -q` on an affected terminal:

Fix non-transparent border on newly spawned urxvt terminals

---

pywal/colors.py

Popen has more power than what is needed for running image magick.  If we use run() there will no longer be resources left open by the sub-process, so we get better house keeping.

Use run instead of popen so that things are closed correctly

---

setup.py

This will help with debugging.  Right now it just tells you that pywal needs python 3.5 or newer.

Allow syntax errors to pass up since users should never see any.

---

pywal/templates/colors.yml

The template for YAML currently exports `color"` in place of `color1` and needs to be fixed.

Fix YAML template

---

pywal/export.py
pywal/settings.py
pywal/util.py

You can now create your own template files for use with `pywal`. 
The template files work the exact same way as the built-in files that exist in `~/.cache/wal`, only now you can define your own custom files. The user created files are read from `~/.config/wal/templates` and are exported to `~/.cache/wal`. 
Using this new feature you can also overwrite the built-in files if you need to customize them further. For example; Creating `colors.css` in your user folder will overwrite the built-in `pywal` file.
For a list of the built-in files and for example syntax; see the default list of templates: https://github.com/dylanaraps/pywal/tree/master/pywal/templates
1. Create a file called `colors.toml` in `~/.config/wal/templates`.
2. Populate the file.
```toml
wallpaper = "{wallpaper}"
background …
```

general: Added user template support.

---

pywal/__init__.py
pywal/__main__.py
pywal/colors.py
pywal/settings.py

Since not every `pywal` release makes breaking changes to the cache files themselves, I think it's appropriate to manage two different version numbers, one for the cache files and the one for `pywal` itself, this way the cache files get ignored only on breaking changes, not on every `pywal` release

Use separate versioning for cache files and pywal.

---

pywal/export.py

MacOS could create a .DS_Store file in one of the folders if a .plist file was introduced. This PR introduces a check that .DS_Store files are not evaluated as templates which breaks the entire program if done.

Fixed issue with .DS_Store files

---

pywal/__main__.py
pywal/sequences.py

Pretty simple fix for #207 .  
Didn't want to change parameters of `send` or add overhead with an extra `save` function that `send` would call anyway, so I just added a kwarg to `send`.

Save sequences file even with -s

---

pywal/templates/colors-rofi-dark.rasi
pywal/templates/colors-rofi-light.rasi

There is no default color for rofi button text, so it will become black in dark theme and be hard to see.

Fix rofi template

---

pywal/templates/colors-wal-st.h

st needs another color to build properly. It stands for "reverse cursor" color - I just set it to be the same as the cursor color.

add missing color for newer st

---

pywal/colors.py

I'm not sure, but I believe this assignment is supposed to be the other way around. Currently, invoking wal twice with the same image but different alpha values with -a causes only the first alpha value to ever be used. Switching the assignment fixes that, since the color sequence building references colors["alpha"], not util.Color.alpha_num.

Fix alpha not being set correctly

---

pywal/export.py
pywal/reload.py
pywal/templates/colors-kitty.conf

I added a template file and a reload function for the [kitty](https://sw.kovidgoyal.net/kitty/index.html)  terminal emulator.
If this PR is accepted, consider adding an entry to the wiki on how to setup the colorscheme from the kitty config file (located in `~/.config/kitty/kitty.conf` by default):
`include ~/.cache/wal/colors-kitty.conf`

Add kitty support

---

pywal/templates/colors-putty.reg

Fix all color values and instead of writing to the "Default Session",
create a new one called "pywal".
Modifying the "Default Session" should be considered bad practice.

fixes the putty template

---

pywal/export.py
pywal/templates/colors-speedcrunch.json

**SpeedCrunch** is a high-precision scientific calculator featuring a fast, keyboard-driven user interface. It is free and open-source software, licensed under the GPL.
```bash
mkdir -p ~/.local/share/SpeedCrunch/color-schemes
ln -sf ~/.cache/wal/colors-speedcrunch.json ~/.local/share/SpeedCrunch/color-schemes/wal.json
```

export: add speedcrunch template

---

pywal/util.py

Fixed pidof invalid argument on Mac OS

---

pywal/__main__.py
pywal/image.py

Fix https://github.com/dylanaraps/pywal/issues/270
* Add a new optional command line argument: `--recursive`, to use with `-i`
* Uses all images from subdirectories
* Works with random and iterative method
I tested it with this structure:
```
test-dir
├── dir1
│   ├── dir11
│   │   └── img_dir11.jpg
│   └── img_dir1.jpg
├── dir2
│   ├── img_dir21.JPG
│   └── img_dir2.jpg
├── dir3
│   ├── img_dir3.jpg
│   └── wrong_file_type.sh
├── img_root1.jpg
└── img_root2.jpg
```
Let me know what you think!
<sup>Feel free to sqash the commits btw, I fought with Travis over the indentation of a single line.</sup>

Add support for #270:  Recursive -i argument

---

pywal/__main__.py

Alternative of https://github.com/dylanaraps/pywal/pull/450 as discussed: https://github.com/dylanaraps/pywal/pull/450#issuecomment-530261257.
Now you can use `-w` to use the last used wallpaper, and combine it with `-l` to generate a light theme from it. It's a separate flag from `-R`.
Please see if this is better @dylanaraps & @927589452 than the original way.

[Feature] Use last used wallpaper for color generation

---

pywal/__main__.py

>It would be very nice to use `wal -R` to switch between the dark and the light version of a theme (from a picture)
>
>eg:
>`wal -R` restores the last theme
>`wal -R -l` gets a light theme from the image
>`wal -R -d` gets a dark theme from the image
>and if these were non image themes it could just switch to behave like `wal -R` without flags

[Feature] Make wal -R understand the -l flag

---

pywal/theme.py

* Prints `(last used`) next to last used theme when listing themes with `--theme`.
I couldn't decide on a symbol to use, so I just used text. If @ghost or someone else has a suggestion, feel free to let me know.
-- 
Closes #305

[Enhancement] #305: Add indication next to previous theme when running wal --theme

---

pywal/theme.py

Slight oversight on my part regarding #456:
* **Bug**: When the theme has never been set, retrieval of the previous theme threw an error (`FileNotFoundError`).
* **Fix**: Fixed it now by checking for the existence of the previous theme.
I realized it almost immediately after the MR was merged, but just got home now to push a fix, sorry about that.

[Bug] Fix error if theme has never been set

---

pywal/reload.py

Reverts from using `Popen` to using `run` due to the reasons explained in issue #491

reload: revert to using subprocess.run to wait for each merge to finish

---

pywal/export.py

Hi,
I was having problems with the template system where strings not between brackets were being replaced. 
To reproduce this issue add the following template:
```
background = {background.rbg}
```
It creates a file with:
```
color0A0E1F =10,14,31 
```
I think this is due to the changes done to allow for calling `util.Color` methods from the template file. I fixed it for my use case however, I have not tested it thoroughly. 
I will leave this here, feel free to do whatever you want with it, and hopefully it might help someone out.

fix template issue

---

pywal/templates/colors-kitty.conf
pywal/util.py

`kitty` expects its [background opacity](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.background_opacity) to be defined as a decimal. This is currently not supported.
This PR adds support for this, but depends on #485 or #496. I updated the default kitty template file. I suggest to edit the wiki as well.

alpha decimal support

---

pywal/export.py

This should have probably been `re.sub` (with a callable replacer) instead of `re.finditer` + `l.replace`, by the way.
Template-side counterpart: https://github.com/dylanaraps/pywal/blob/eb4200820b13006e2434bbc0bb402ed89726d042/pywal/templates/colors-kitty.conf#L3
Relevant: #525

Fix for kitty alpha_dec replacer

---

pywal/sequences.py

There is a small typo in pywal/sequences.py.
Should read `foreground` rather than `foregound`.

docs: Fix simple typo, foregound -> foreground

---

pywal/colors.py

- Windows path isn't escaped when passed through JSON.dump
- This prevents it from being loaded in nodejs or being processed by PowerShell's ConvertFrom-Json
This change uses forward slash when outputting the wallpaper path

fix: Wallpaper path on Windows isn't JSON compliant

---

pywal/templates/colors-rofi-dark.rasi
pywal/templates/colors-rofi-light.rasi

New version of Rofi has certain issues with old themes, particularly with font and background colors. Updated templates accordingly.
See
https://github.com/davatorium/rofi/issues/1397
https://github.com/davatorium/rofi/releases/tag/1.7.0

Updated templates to be compatible with rofi 1.7.0^

---

pywal/backends/fast_colorthief.py

colorthief is a very nice pywal backend, but takes quite a while to run.
[this implementation](https://github.com/bedapisl/fast-colorthief) is based on the currently used colorthief library, but runs the color extraction in c++, giving ~15x faster results.
in testing this shows up in `pywal --backend` as expected, runs well, and generates visually identical palettes.

add fast_colorthief backend
